version: '3'
services:
  # Nginx server configuration
  web:
    network_mode: bridge
    image: nginx:1.17
    container_name: webserver
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"

  # Php-fpm configuration
  php:
    container_name: php-fpm
    network_mode: bridge
    build:
      context: .
    volumes:
      - ./src:/var/www/html


